######################################################################
# Automatically generated by qmake (2.01a) lun. déc. 20 21:35:26 2010
######################################################################

TEMPLATE = app
TARGET =

macx:QMAKE_CC=/usr/bin/clang
macx:QMAKE_CXX=/usr/bin/clang++

QT *= opengl xml
CONFIG += qt  warn_on  boost


DEFINES += WITH_VISU3D_QGLVIEWER

LIBS += -lDGtal -lDGtalIO  -lboost_program_options  -lQGLViewer

# Input


SOURCES += seedsGenerator.cpp
